"""Packaging contract: the console scripts must actually be installed.

Why this file exists
--------------------
Versions 1.0.17-1.0.22 shipped with *no working console scripts at all*
("command not found" for ``idun``, ``idun-multi``, ``idun-mcp``) while the
whole test suite stayed green. The regression was introduced in commit
cfcadf9, which added a ``[project]`` table to pyproject.toml. Under PEP 621
that table wins over ``setup.py``, so the ``entry_points`` declared in
setup.py were silently ignored.

Nothing in the suite caught it because every other test imports the modules
directly (``import idun_multi``), which works fine regardless of whether an
entry point was ever generated. Verifying the *packaging* requires looking at
installed metadata, not at imports.

These tests are deliberately written against the installed distribution rather
than the source tree, and they are skipped (not failed) when the package is not
installed, so a bare ``pytest`` in a fresh checkout stays usable.
"""
from __future__ import annotations

import subprocess
import sys

import pytest

# The three console scripts the project promises (setup.py entry_points,
# README, and install.sh all reference exactly these).
EXPECTED_SCRIPTS = ("idun", "idun-multi", "idun-mcp")

# idun-mcp is an MCP stdio server (JSON-RPC over stdin/stdout), not an
# argparse CLI: main() reads stdin and exits cleanly on EOF, so it produces no
# --help output by design. Only the argparse-based CLIs are checked for help
# output; idun-mcp is still covered by the declaration/import/exit-code tests.
HELP_SCRIPTS = ("idun", "idun-multi")

DIST_NAME = "idun-sdk"


def _dist():
    """Return the installed distribution, or None when not installed."""
    from importlib.metadata import PackageNotFoundError, distribution
    try:
        return distribution(DIST_NAME)
    except PackageNotFoundError:
        return None


requires_install = pytest.mark.skipif(
    _dist() is None,
    reason=f"{DIST_NAME} is not installed; packaging contract not applicable",
)


@requires_install
@pytest.mark.parametrize("name", EXPECTED_SCRIPTS)
def test_console_script_is_declared(name):
    """Each promised script must exist as a console_scripts entry point.

    This is the check that fails on 1.0.17-1.0.22 and passes on 1.0.16.
    """
    dist = _dist()
    console = {
        ep.name for ep in dist.entry_points if ep.group == "console_scripts"
    }
    assert name in console, (
        f"console script {name!r} is not declared in the installed metadata "
        f"(found: {sorted(console) or 'none'}). Most likely pyproject.toml has "
        f"a [project] table but no [project.scripts], which makes PEP 621 "
        f"ignore the entry_points in setup.py."
    )


@requires_install
@pytest.mark.parametrize("name", EXPECTED_SCRIPTS)
def test_console_script_target_is_importable(name):
    """The entry point must resolve to a real callable, not a dangling path.

    A declared-but-broken entry point would still give the user a traceback
    instead of a working command, so declaring it is not enough.
    """
    dist = _dist()
    eps = {
        ep.name: ep for ep in dist.entry_points if ep.group == "console_scripts"
    }
    ep = eps.get(name)
    if ep is None:
        pytest.fail(f"console script {name!r} is not declared at all")
    target = ep.load()  # raises if the module or attribute is missing
    assert callable(target), f"entry point {name!r} does not resolve to a callable"


@requires_install
@pytest.mark.parametrize("name", HELP_SCRIPTS)
def test_console_script_runs_help(name):
    """``<script> --help`` must exit 0 when invoked as a real subprocess.

    Import-based tests cannot catch a missing wrapper script; only actually
    executing the command can. Restricted to HELP_SCRIPTS because idun-mcp is
    a stdio server with no --help surface.
    """
    import shutil
    exe = shutil.which(name)
    if exe is None:
        pytest.fail(
            f"{name!r} is declared but not on PATH -- the wrapper script was "
            f"not generated by the installer"
        )
    proc = subprocess.run(
        [exe, "--help"],
        capture_output=True,
        text=True,
        timeout=120,
        stdin=subprocess.DEVNULL,
    )
    assert proc.returncode == 0, (
        f"{name} --help exited {proc.returncode}\n"
        f"stdout: {proc.stdout[:500]}\nstderr: {proc.stderr[:500]}"
    )
    assert proc.stdout.strip() or proc.stderr.strip(), (
        f"{name} --help produced no output at all"
    )


@requires_install
@pytest.mark.parametrize("name", EXPECTED_SCRIPTS)
def test_console_script_wrapper_exists_and_exits_cleanly(name):
    """Every promised script must exist on PATH and not crash on startup.

    This is the check that maps directly to the user-visible symptom of
    1.0.17-1.0.22: "command not found". Covers idun-mcp too, which is fed an
    empty stdin so the stdio server reaches EOF and shuts down normally.
    """
    import shutil
    exe = shutil.which(name)
    assert exe is not None, (
        f"{name!r} is not on PATH -- this is the 'command not found' symptom "
        f"that shipped in 1.0.17-1.0.22"
    )
    proc = subprocess.run(
        [exe, "--help"],
        capture_output=True,
        text=True,
        timeout=120,
        stdin=subprocess.DEVNULL,
    )
    assert proc.returncode == 0, (
        f"{name} exited {proc.returncode} on startup\n"
        f"stderr: {proc.stderr[:500]}"
    )
    assert "Traceback" not in proc.stderr, (
        f"{name} raised on startup:\n{proc.stderr[:800]}"
    )


@requires_install
def test_no_metadata_duplication_for_scripts():
    """Guard the root cause, not just the symptom.

    setup.py and pyproject.toml both carrying project metadata is what caused
    the regression: entry_points lived only in setup.py while pyproject.toml
    owned [project]. If a [project] table exists, it must also own the scripts.
    """
    import os
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    pyproject = os.path.join(root, "pyproject.toml")
    if not os.path.exists(pyproject):
        pytest.skip("no pyproject.toml in this checkout")
    with open(pyproject, encoding="utf-8") as fh:
        text = fh.read()
    if "[project]" not in text:
        pytest.skip("pyproject.toml declares no [project] table")
    assert "[project.scripts]" in text, (
        "pyproject.toml has a [project] table but no [project.scripts]. "
        "Under PEP 621 this makes setuptools ignore entry_points from "
        "setup.py, so no console scripts get installed."
    )
